name: raspberry_system_monitor_server
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.3.0+1

dev_dependencies:
  test: any
  aqueduct_test: ^1.0.0